import { z } from "zod";

/**
 * Zod schemas that mirror the domain types in types/index.ts.
 *
 * These are used to validate the raw JSON returned by the LLM before it is
 * trusted by the rest of the system. The LLM is instructed to follow this
 * shape, but we treat its output as untrusted and coerce where it is safe.
 */

const severity = z.enum(["Low", "Medium", "High", "Critical"]);
const likelihood = z.enum(["Low", "Medium", "High"]);
const deploymentPattern = z.enum(["Single AZ", "Multi AZ", "Cross Region DR"]);

export const designDecisionSchema = z.object({
  component: z.string().min(1),
  rationale: z.string().min(1),
  advantages: z.array(z.string()).default([]),
  tradeOffs: z.array(z.string()).default([]),
});

export const riskSchema = z.object({
  id: z.string().min(1),
  category: z.string().min(1),
  description: z.string().min(1),
  severity,
  likelihood,
});

export const mitigationSchema = z.object({
  riskId: z.string().min(1),
  strategy: z.string().min(1),
  actions: z.array(z.string()).default([]),
});

export const deploymentSchema = z.object({
  pattern: deploymentPattern,
  rationale: z.string().min(1),
  topology: z.array(z.string()).default([]),
  drObjective: z.object({
    rto: z.string().min(1),
    rpo: z.string().min(1),
  }),
});

export const componentsSchema = z.object({
  frontend: z.string(),
  backend: z.string(),
  apiLayer: z.string(),
  loadBalancer: z.string(),
  database: z.string(),
  cache: z.string(),
  messageQueue: z.string(),
  objectStorage: z.string(),
  monitoring: z.string(),
  logging: z.string(),
  security: z.string(),
  disasterRecovery: z.string(),
  network: z.string(),
});

/**
 * The full solution payload expected from the LLM (meta is added by the server,
 * not generated by the model). Stripped to the keys the model produces.
 */
export const llmSolutionSchema = z.object({
  executiveSummary: z.string().min(1),
  components: componentsSchema,
  mermaidDiagram: z.string().min(1),
  designDecisions: z.array(designDecisionSchema).default([]),
  risks: z.array(riskSchema).default([]),
  mitigations: z.array(mitigationSchema).default([]),
  deployment: deploymentSchema,
});

export type LlmSolution = z.infer<typeof llmSolutionSchema>;
