"use client";

import * as React from "react";
import { Info } from "lucide-react";
import { ExportControls } from "@/components/ExportControls";
import { ImprovementActions } from "@/components/ImprovementActions";
import { ExecutiveSummarySection } from "@/components/sections/ExecutiveSummarySection";
import { ArchitectureSection } from "@/components/sections/ArchitectureSection";
import { DiagramSection } from "@/components/sections/DiagramSection";
import { DesignDecisionsSection } from "@/components/sections/DesignDecisionsSection";
import { RisksSection } from "@/components/sections/RisksSection";
import { MitigationsSection } from "@/components/sections/MitigationsSection";
import { DeploymentSection } from "@/components/sections/DeploymentSection";
import { AiServicesSection } from "@/components/sections/AiServicesSection";
import { getImprovementConfig } from "@/lib/llm/improvements";
import type { ArchitectureSolution, ImprovementFocus, SectionKey } from "@/types";

export function SolutionView({
  solution,
  onImprove,
  activeFocus,
  isRegenerating,
}: {
  solution: ArchitectureSolution;
  onImprove: (focus: ImprovementFocus) => void;
  activeFocus: ImprovementFocus | null;
  isRegenerating: boolean;
}) {
  const regeneratingSections = React.useMemo<Set<SectionKey>>(() => {
    if (!activeFocus) return new Set();
    return new Set(getImprovementConfig(activeFocus).sections);
  }, [activeFocus]);

  const is = (key: SectionKey) => regeneratingSections.has(key);

  return (
    <div className="space-y-4">
      <ExportControls solution={solution} />
      <ImprovementActions
        onImprove={onImprove}
        activeFocus={activeFocus}
        disabled={isRegenerating}
      />

      <div className="space-y-4">
        <ExecutiveSummarySection
          summary={solution.executiveSummary}
          regenerating={is("executiveSummary")}
        />
        <ArchitectureSection
          components={solution.components}
          regenerating={is("components")}
        />
        <DiagramSection
          diagram={solution.mermaidDiagram}
          regenerating={is("mermaidDiagram")}
        />
        <DesignDecisionsSection
          decisions={solution.designDecisions}
          regenerating={is("designDecisions")}
        />
        <RisksSection risks={solution.risks} regenerating={is("risks")} />
        <MitigationsSection
          mitigations={solution.mitigations}
          regenerating={is("mitigations")}
        />
        <DeploymentSection
          deployment={solution.deployment}
          regenerating={is("deployment")}
        />
        {solution.aiSection ? (
          <AiServicesSection aiSection={solution.aiSection} />
        ) : null}
      </div>

      <div className="flex items-start gap-2 rounded-lg border border-slate-200 bg-slate-50/60 px-3 py-2.5 text-xs text-slate-500 dark:border-slate-800 dark:bg-slate-900/40 dark:text-slate-400">
        <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" />
        <span>
          Generated by {solution.meta.provider} using{" "}
          <span className="font-medium text-slate-600 dark:text-slate-300">
            {solution.meta.model}
          </span>
          . This is an AI-assisted proposal — validate technical fit, pricing,
          and compliance with your cloud provider before commitment.
        </span>
      </div>
    </div>
  );
}
