import type { ArchitectureSolution } from "@/types";
import { COMPONENT_FIELDS } from "@/types";

/**
 * Client-side export helpers: Markdown download, PDF (via a hidden print
 * iframe), and clipboard copy. All run in the browser from button handlers.
 */

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke on the next tick so the download has time to start.
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

/* -------------------------------------------------------------------------- */
/* Markdown                                                                   */
/* -------------------------------------------------------------------------- */

export function solutionToMarkdown(s: ArchitectureSolution): string {
  const lines: string[] = [];
  const push = (str = "") => lines.push(str);

  push(`# Enterprise Architecture Proposal`);
  push();
  push(`> Generated by AI Solution Architect — ${s.meta.provider} (${s.meta.model}) on ${formatDate(s.meta.generatedAt)}.${s.meta.focus ? ` Focus: ${s.meta.focus}.` : ""}`);
  push();
  push(`---`);
  push();

  push(`## 1. Executive Summary`);
  push();
  push(s.executiveSummary);
  push();

  push(`## 2. Proposed Architecture`);
  push();
  for (const { label, key } of COMPONENT_FIELDS) {
    push(`### ${label}`);
    push();
    push(s.components[key]);
    push();
  }

  push(`## 3. Architecture Diagram`);
  push();
  push("```mermaid");
  push(stripMermaidFences(s.mermaidDiagram));
  push("```");
  push();

  push(`## 4. Design Decisions`);
  push();
  for (const d of s.designDecisions) {
    push(`### ${d.component}`);
    push();
    push(d.rationale);
    push();
    push(`**Advantages**`);
    for (const a of d.advantages) push(`- ${a}`);
    push();
    push(`**Trade-offs**`);
    for (const t of d.tradeOffs) push(`- ${t}`);
    push();
  }

  push(`## 5. Risks`);
  push();
  push(`| ID | Category | Description | Severity | Likelihood |`);
  push(`| --- | --- | --- | --- | --- |`);
  for (const r of s.risks) {
    push(`| ${r.id} | ${r.category} | ${r.description} | ${r.severity} | ${r.likelihood} |`);
  }
  push();

  push(`## 6. Mitigations`);
  push();
  for (const m of s.mitigations) {
    push(`### ${m.riskId} — ${m.strategy}`);
    push();
    for (const a of m.actions) push(`- ${a}`);
    push();
  }

  push(`## 7. Deployment Recommendation`);
  push();
  push(`**Pattern:** ${s.deployment.pattern}`);
  push();
  push(s.deployment.rationale);
  push();
  push(`**Topology**`);
  push();
  s.deployment.topology.forEach((step, i) => push(`${i + 1}. ${step}`));
  push();
  push(`**DR Objective:** RTO ${s.deployment.drObjective.rto} / RPO ${s.deployment.drObjective.rpo}`);
  push();

  return lines.join("\n");
}

export function downloadMarkdown(s: ArchitectureSolution): void {
  const md = solutionToMarkdown(s);
  triggerDownload(new Blob([md], { type: "text/markdown;charset=utf-8" }), "architecture-proposal.md");
}

/* -------------------------------------------------------------------------- */
/* PDF (print-to-PDF via hidden iframe)                                       */
/* -------------------------------------------------------------------------- */

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** Minimal markdown -> HTML for bold, inline code, lists, and paragraphs. */
function mdToHtml(text: string): string {
  const escaped = escapeHtml(text);
  const lines = escaped.split("\n");
  const out: string[] = [];
  let inList = false;

  const closeList = () => {
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
  };

  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith("- ") || line.startsWith("* ")) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${inline(line.slice(2))}</li>`);
    } else if (line === "") {
      closeList();
    } else {
      closeList();
      out.push(`<p>${inline(line)}</p>`);
    }
  }
  closeList();
  return out.join("\n");
}

function inline(text: string): string {
  return text
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}

function stripMermaidFences(code: string): string {
  const m = code.trim().match(/```(?:mermaid)?\s*([\s\S]*?)```/i);
  return (m?.[1] ?? code).trim();
}

function severityClass(sev: string): string {
  switch (sev) {
    case "Critical":
      return "sev-critical";
    case "High":
      return "sev-high";
    case "Medium":
      return "sev-medium";
    default:
      return "sev-low";
  }
}

export function downloadPdf(s: ArchitectureSolution): void {
  // Grab the rendered mermaid SVG from the DOM if present, so the PDF shows
  // the actual diagram rather than just source code.
  const svg = document
    .querySelector("[data-mermaid-container] svg")
    ?.outerHTML?.replace(/<svg/, '<svg style="max-width:100%;height:auto"');

  const componentRows = COMPONENT_FIELDS.map(
    ({ label, key }) => `
      <div class="component">
        <div class="component-label">${label}</div>
        <div class="component-value">${mdToHtml(s.components[key])}</div>
      </div>`,
  ).join("");

  const decisionBlocks = s.designDecisions
    .map(
      (d) => `
      <div class="decision">
        <h4>${escapeHtml(d.component)}</h4>
        <div>${mdToHtml(d.rationale)}</div>
        <p class="subhead">Advantages</p>
        ${listToHtml(d.advantages)}
        <p class="subhead">Trade-offs</p>
        ${listToHtml(d.tradeOffs)}
      </div>`,
    )
    .join("");

  const riskRows = s.risks
    .map(
      (r) => `
      <tr>
        <td>${escapeHtml(r.id)}</td>
        <td>${escapeHtml(r.category)}</td>
        <td>${escapeHtml(r.description)}</td>
        <td><span class="sev ${severityClass(r.severity)}">${r.severity}</span></td>
        <td>${r.likelihood}</td>
      </tr>`,
    )
    .join("");

  const mitigationBlocks = s.mitigations
    .map(
      (m) => `
      <div class="mitigation">
        <h4>${escapeHtml(m.riskId)} — ${escapeHtml(m.strategy)}</h4>
        ${listToHtml(m.actions)}
      </div>`,
    )
    .join("");

  const topology = s.deployment.topology
    .map((step, i) => `<li>${escapeHtml(step)}</li>`)
    .join("");

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Enterprise Architecture Proposal</title>
<style>
  @page { size: A4; margin: 18mm 16mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1e293b; font-size: 12px; line-height: 1.55; }
  h1 { font-size: 22px; color: #1d4ed8; margin: 0 0 4px; }
  h2 { font-size: 16px; color: #1e3a8a; border-bottom: 2px solid #dbeafe; padding-bottom: 4px; margin: 26px 0 10px; }
  h3 { font-size: 13px; color: #1e40af; margin: 14px 0 6px; }
  h4 { font-size: 12px; color: #1d4ed8; margin: 12px 0 4px; }
  p { margin: 6px 0; }
  .meta { color: #64748b; font-size: 11px; margin-bottom: 12px; }
  .component { margin: 6px 0; padding: 8px 10px; background: #f8fafc; border-left: 3px solid #2563eb; border-radius: 4px; }
  .component-label { font-weight: 600; color: #1e3a8a; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; margin-bottom: 2px; }
  .component-value p { margin: 2px 0; }
  ul { margin: 4px 0 4px 18px; padding: 0; }
  li { margin: 2px 0; }
  .subhead { font-weight: 600; color: #475569; font-size: 11px; margin: 8px 0 2px; text-transform: uppercase; letter-spacing: .03em; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 11px; }
  th { background: #1e3a8a; color: #fff; text-align: left; padding: 6px 8px; }
  td { border: 1px solid #e2e8f0; padding: 6px 8px; vertical-align: top; }
  tr:nth-child(even) td { background: #f8fafc; }
  .sev { padding: 1px 6px; border-radius: 10px; font-size: 10px; font-weight: 600; color: #fff; }
  .sev-critical { background: #b91c1c; }
  .sev-high { background: #ea580c; }
  .sev-medium { background: #ca8a04; }
  .sev-low { background: #16a34a; }
  .decision, .mitigation { margin: 8px 0; padding: 8px 10px; border: 1px solid #e2e8f0; border-radius: 6px; }
  .dr { display: flex; gap: 12px; margin-top: 8px; }
  .dr div { flex: 1; background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 8px 10px; }
  .dr .label { font-size: 10px; color: #1d4ed8; text-transform: uppercase; letter-spacing: .05em; }
  .dr .value { font-size: 16px; font-weight: 700; color: #1e3a8a; }
  .diagram { margin: 10px 0; padding: 12px; border: 1px solid #e2e8f0; border-radius: 6px; text-align: center; }
  .break { page-break-before: always; }
</style>
</head>
<body>
  <h1>Enterprise Architecture Proposal</h1>
  <div class="meta">Generated by AI Solution Architect — ${escapeHtml(s.meta.provider)} (${escapeHtml(s.meta.model)}) on ${escapeHtml(formatDate(s.meta.generatedAt))}.${s.meta.focus ? ` Focus: ${escapeHtml(s.meta.focus)}.` : ""}</div>

  <h2>1. Executive Summary</h2>
  ${mdToHtml(s.executiveSummary)}

  <h2 class="break">2. Proposed Architecture</h2>
  ${componentRows}

  <h2 class="break">3. Architecture Diagram</h2>
  ${svg ? `<div class="diagram">${svg}</div>` : `<pre style="white-space:pre-wrap;font-size:10px">${escapeHtml(stripMermaidFences(s.mermaidDiagram))}</pre>`}

  <h2 class="break">4. Design Decisions</h2>
  ${decisionBlocks}

  <h2 class="break">5. Risks</h2>
  <table>
    <thead><tr><th>ID</th><th>Category</th><th>Description</th><th>Severity</th><th>Likelihood</th></tr></thead>
    <tbody>${riskRows}</tbody>
  </table>

  <h2 class="break">6. Mitigations</h2>
  ${mitigationBlocks}

  <h2 class="break">7. Deployment Recommendation</h2>
  <h3>Pattern: ${escapeHtml(s.deployment.pattern)}</h3>
  ${mdToHtml(s.deployment.rationale)}
  <h3>Topology</h3>
  <ol>${topology}</ol>
  <h3>Disaster Recovery Objective</h3>
  <div class="dr">
    <div><div class="label">RTO</div><div class="value">${escapeHtml(s.deployment.drObjective.rto)}</div></div>
    <div><div class="label">RPO</div><div class="value">${escapeHtml(s.deployment.drObjective.rpo)}</div></div>
  </div>
</body>
</html>`;

  // Write into a hidden iframe and trigger its print dialog (Save as PDF).
  const existing = document.getElementById("__pdf_frame__");
  if (existing) existing.remove();

  const iframe = document.createElement("iframe");
  iframe.id = "__pdf_frame__";
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow?.document;
  if (!doc) return;
  doc.open();
  doc.write(html);
  doc.close();

  const win = iframe.contentWindow;
  const cleanup = () => iframe.remove();
  iframe.onload = () => {
    win?.focus();
    win?.print();
    // Give the browser a moment after the print dialog is dismissed.
    setTimeout(cleanup, 1000);
  };
}

function listToHtml(items: string[]): string {
  if (items.length === 0) return "<p><em>—</em></p>";
  return `<ul>${items.map((i) => `<li>${escapeHtml(i)}</li>`).join("")}</ul>`;
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    });
  } catch {
    return iso;
  }
}

/* -------------------------------------------------------------------------- */
/* Clipboard                                                                  */
/* -------------------------------------------------------------------------- */

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    /* fall through to legacy path */
  }
  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    ta.remove();
    return ok;
  } catch {
    return false;
  }
}
